apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: dbex
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: https://github.com/CCI-MOC/dbex.git
    contextDir: /
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile.dbex
  output:
    to:
      kind: ImageStreamTag
      name: dbex:latest
